/*
 * generated by Xtext 2.16.0
 */
package fr.atsyra.abat.ide

import com.google.inject.Guice
import fr.atsyra.abat.AbatRuntimeModule
import fr.atsyra.abat.AbatStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AbatIdeSetup extends AbatStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new AbatRuntimeModule, new AbatIdeModule))
	}
	
}
