/*
 * generated by Xtext 2.16.0
 */
package fr.atsyra.abat


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AbatRuntimeModule extends AbstractAbatRuntimeModule {
}
