/*
 * generated by Xtext 2.16.0
 */
package fr.atsyra.abat


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AbatStandaloneSetup extends AbatStandaloneSetupGenerated {

	def static void doSetup() {
		new AbatStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
