/*
 * generated by Xtext 2.16.0
 */
package fr.atsyra.abat.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import fr.atsyra.abat.abat.AttackTree

@ExtendWith(InjectionExtension)
@InjectWith(AbatInjectorProvider)
class AbatParsingTest {
	@Inject
	ParseHelper<AttackTree> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			AND(SAND("a","b"),SAND("a","b"))
		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}
}
